### ISSUE TITLE
Access to the path is denied. [C:\Projects\.....dotnet-kubernetes\Products\Products.csproj]

### ISSUE THREAD

**Issue by eliassal** [MicrosoftDocs/mslearn-dotnet-cloudnative#14]
After following instructions up to step 2
`dotnet publish /p:PublishProfile=DefaultContainer`

Building the product image errored as follows

> Building image 'products' with tags 'latest' on top of base image 'mcr.microsoft.com/dotnet/aspnet:8.0'.
> C:\Program Files\dotnet\sdk\8.0.106\Containers\build\Microsoft.NET.Build.Containers.targets(202,5): error MSB4018: The "CreateNewImage" task failed unexpectedly. [C:\Projects\AzureDevOpsProjects\MSLearn\mslear
> n-dotnet-cloudnative\dotnet-kubernetes\Products\Products.csproj]
> C:\Program Files\dotnet\sdk\8.0.106\Containers\build\Microsoft.NET.Build.Containers.targets(202,5): error MSB4018: System.UnauthorizedAccessException: Access to the path is denied. [C:\Projects\AzureDevOpsProj
> ects\MSLearn\mslearn-dotnet-cloudnative\dotnet-kubernetes\Products\Products.csproj]

whereas store image was build correctly. Why is this and what is needed to be done? Thanks
![image](https://github.com/MicrosoftDocs/mslearn-dotnet-cloudnative/assets/8447864/d78bd8ad-34b0-4c47-8be1-ef3cc666aa84)

**Comment by jamesmontemagno** [comment]
are you running this locally on your machine or in a github codespace?

**Comment by jamesmontemagno** [comment]
It built up locally here fine for me locally. Are you able to update to the latest .NET SDK: https://dotnet.microsoft.com/en-us/download looks like you are on an older one.

**Comment by eliassal** [comment]
Hi, I a running eberything locally. Dear @jamesmontemagno  I have latest .Net SDK

![image](https://github.com/MicrosoftDocs/mslearn-dotnet-cloudnative/assets/8447864/1b76ea73-875a-45f8-bc91-a72e7c78a6eb)

I tried both dotnet docker and kubernetes, both have issues with the product image

**Comment by jamesmontemagno** [comment]
8.0.300 is the latest sdk if you can try that.. https://dotnet.microsoft.com/en-us/download

Let me also ping @baronfel if he has any idea

**Comment by baronfel** [comment]
My guess is a timing issue here - when you run `dotnet publish` at the solution level you end up containerizing both projects at the same time. This means that each project is doing the following in parallel:

* reading the image manifest to determine which base image should be used
* downloading the image layers for you for your base image
* creating the new image for your app

this second step involves downloading files from your container registry and storing them locally in your system, but if both projects use the same base image (probably `dotnet/aspnet`?) this can lead to a race condition where only the first one finished downloading can successfully copy. My guess is that if you ran the publish again both would succeed because you would have already downloaded all the images. Does this match the behavior you see? We have an issue tracking fixing this at https://github.com/dotnet/sdk-container-builds/issues/344.
